-- Irregular Verbs Data Import
-- Insert irregular verb conjugations for the 10 most common Portuguese irregular verbs
-- Mapping to actual database column names

INSERT INTO public.irregular_verbs (infinitive, presente_ind_eu, presente_ind_tu, presente_ind_ele_ela, presente_ind_nos, presente_ind_vos, presente_ind_eles_elas, pps_eu, pps_tu, pps_ele_ela, pps_nos, pps_vos, pps_eles_elas, pret_imp_eu, pret_imp_tu, pret_imp_ele_ela, pret_imp_nos, pret_imp_vos, pret_imp_eles_elas, fut_imp_eu, fut_imp_tu, fut_imp_ele_ela, fut_imp_nos, fut_imp_vos, fut_imp_eles_elas, conj_pres_eu, conj_pres_tu, conj_pres_ele_ela, conj_pres_nos, conj_pres_vos, conj_pres_eles_elas, cond_pres_eu, cond_pres_tu, cond_pres_ele_ela, cond_pres_nos, cond_pres_vos, cond_pres_eles_elas, imp_pos_tu, imp_pos_ele_ela, imp_pos_nos, imp_pos_vos, imp_pos_eles_elas, participio_passado) VALUES
('ser', 'sou', 'és', 'é', 'somos', 'sois', 'são', 'fui', 'foste', 'foi', 'fomos', 'fostes', 'foram', 'era', 'eras', 'era', 'éramos', 'éreis', 'eram', 'serei', 'serás', 'será', 'seremos', 'sereis', 'serão', 'seja', 'sejas', 'seja', 'sejamos', 'sejais', 'sejam', 'seria', 'serias', 'seria', 'seríamos', 'seríeis', 'seriam', 'sê', 'seja', 'sejamos', 'sede', 'sejam', 'sido'),
('estar', 'estou', 'estás', 'está', 'estamos', 'estais', 'estão', 'estive', 'estiveste', 'esteve', 'estivemos', 'estivestes', 'estiveram', 'estava', 'estavas', 'estava', 'estávamos', 'estáveis', 'estavam', 'estarei', 'estarás', 'estará', 'estaremos', 'estareis', 'estarão', 'esteja', 'estejas', 'esteja', 'estejamos', 'estejais', 'estejam', 'estaria', 'estarias', 'estaria', 'estaríamos', 'estaríeis', 'estariam', 'está', 'esteja', 'estejamos', 'estai', 'estejam', 'estado'),
('ter', 'tenho', 'tens', 'tem', 'temos', 'tendes', 'têm', 'tive', 'tiveste', 'teve', 'tivemos', 'tivestes', 'tiveram', 'tinha', 'tinhas', 'tinha', 'tínhamos', 'tínheis', 'tinham', 'terei', 'terás', 'terá', 'teremos', 'tereis', 'terão', 'tenha', 'tenhas', 'tenha', 'tenhamos', 'tenhais', 'tenham', 'teria', 'terias', 'teria', 'teríamos', 'teríeis', 'teriam', 'tem', 'tenha', 'tenhamos', 'tende', 'tenham', 'tido'),
('ir', 'vou', 'vais', 'vai', 'vamos', 'ides', 'vão', 'fui', 'foste', 'foi', 'fomos', 'fostes', 'foram', 'ia', 'ias', 'ia', 'íamos', 'íeis', 'iam', 'irei', 'irás', 'irá', 'iremos', 'ireis', 'irão', 'vá', 'vás', 'vá', 'vamos', 'vades', 'vão', 'iria', 'irias', 'iria', 'iríamos', 'iríeis', 'iriam', 'vai', 'vá', 'vamos', 'ide', 'vão', 'ido'),
('fazer', 'faço', 'fazes', 'faz', 'fazemos', 'fazeis', 'fazem', 'fiz', 'fizeste', 'fez', 'fizemos', 'fizestes', 'fizeram', 'fazia', 'fazias', 'fazia', 'fazíamos', 'fazíeis', 'faziam', 'farei', 'farás', 'fará', 'faremos', 'fareis', 'farão', 'faça', 'faças', 'faça', 'façamos', 'façais', 'façam', 'faria', 'farias', 'faria', 'faríamos', 'faríeis', 'fariam', 'faz', 'faça', 'façamos', 'fazei', 'façam', 'feito'),
('poder', 'posso', 'podes', 'pode', 'podemos', 'podeis', 'podem', 'pude', 'pudeste', 'pôde', 'pudemos', 'pudestes', 'puderam', 'podia', 'podias', 'podia', 'podíamos', 'podíeis', 'podiam', 'poderei', 'poderás', 'poderá', 'poderemos', 'podereis', 'poderão', 'possa', 'possas', 'possa', 'possamos', 'possais', 'possam', 'poderia', 'poderias', 'poderia', 'poderíamos', 'poderíeis', 'poderiam', 'pode', 'possa', 'possamos', 'podei', 'possam', 'podido'),
('dizer', 'digo', 'dizes', 'diz', 'dizemos', 'dizeis', 'dizem', 'disse', 'disseste', 'disse', 'dissemos', 'dissestes', 'disseram', 'dizia', 'dizias', 'dizia', 'dizíamos', 'dizíeis', 'diziam', 'direi', 'dirás', 'dirá', 'diremos', 'direis', 'dirão', 'diga', 'digas', 'diga', 'digamos', 'digais', 'digam', 'diria', 'dirias', 'diria', 'diríamos', 'diríeis', 'diriam', 'diz', 'diga', 'digamos', 'dizei', 'digam', 'dito'),
('vir', 'venho', 'vens', 'vem', 'vimos', 'vindes', 'vêm', 'vim', 'vieste', 'veio', 'viemos', 'viestes', 'vieram', 'vinha', 'vinhas', 'vinha', 'vínhamos', 'vínheis', 'vinham', 'virei', 'virás', 'virá', 'viremos', 'vireis', 'virão', 'venha', 'venhas', 'venha', 'venhamos', 'venhais', 'venham', 'viria', 'virias', 'viria', 'viríamos', 'viríeis', 'viriam', 'vem', 'venha', 'venhamos', 'vinde', 'venham', 'vindo'),
('dar', 'dou', 'dás', 'dá', 'damos', 'dais', 'dão', 'dei', 'deste', 'deu', 'demos', 'destes', 'deram', 'dava', 'davas', 'dava', 'dávamos', 'dáveis', 'davam', 'darei', 'darás', 'dará', 'daremos', 'dareis', 'darão', 'dê', 'dês', 'dê', 'dêmos', 'deis', 'dêem', 'daria', 'darias', 'daria', 'daríamos', 'daríeis', 'dariam', 'dá', 'dê', 'dêmos', 'dai', 'dêem', 'dado'),
('saber', 'sei', 'sabes', 'sabe', 'sabemos', 'sabeis', 'sabem', 'soube', 'soubeste', 'soube', 'soubemos', 'soubestes', 'souberam', 'sabia', 'sabias', 'sabia', 'sabíamos', 'sabíeis', 'sabiam', 'saberei', 'saberás', 'saberá', 'saberemos', 'sabereis', 'saberão', 'saiba', 'saibas', 'saiba', 'saibamos', 'saibais', 'saibam', 'saberia', 'saberias', 'saberia', 'saberíamos', 'saberíeis', 'saberiam', 'sabe', 'saiba', 'saibamos', 'sabei', 'saibam', 'sabido');